import jsPDF from 'jspdf';

export const generateMedicalReport = (result, imageElement, user) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const today = new Date().toLocaleString();

  // --- 1. HEADER SECTION ---
  // Brand Color Bar
  doc.setFillColor(79, 70, 229); // Indigo-600
  doc.rect(0, 0, pageWidth, 25, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text("AquaSmart Diagnostic Report", 15, 17);

  // Sub-details (Right side)
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${today}`, pageWidth - 15, 12, { align: 'right' });
  doc.text(`Officer: ${user ? user.name : 'Unknown'}`, pageWidth - 15, 18, { align: 'right' });

  // --- 2. IMAGE EVIDENCE ---
  // We take the HTML image element passed to this function and add it to PDF
  if (imageElement) {
    try {
      // Add Image (x, y, width, height)
      // Keep aspect ratio roughly square-ish for the report
      doc.addImage(imageElement, 'JPEG', 15, 35, 80, 60);
      
      // Draw a border around image
      doc.setDrawColor(200, 200, 200);
      doc.rect(15, 35, 80, 60);
    } catch (e) {
      console.error("Error adding image to PDF", e);
    }
  }

  // --- 3. DIAGNOSIS SUMMARY (Right of Image) ---
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("Analysis Summary", 105, 42);

  // Status Indicator
  const isHealthy = result.status === 'healthy';
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Condition Detected:`, 105, 52);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(isHealthy ? 0 : 220, isHealthy ? 150 : 20, 60); // Green or Red
  doc.text(result.condition.toUpperCase(), 105, 60);

  // Reset Color
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  doc.text(`Confidence Score: ${result.confidence}%`, 105, 72);
  doc.text(`Risk Level: ${isHealthy ? 'Low' : 'CRITICAL'}`, 105, 80);
  doc.text(`Scan ID: #${Math.floor(Math.random()*100000)}`, 105, 88);

  // --- 4. DETAILED FINDINGS & ACTIONS (Below Image) ---
  let yPos = 110;

  // Section Title
  doc.setFillColor(240, 240, 240);
  doc.rect(15, yPos - 5, pageWidth - 30, 10, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text("AI RECOMMENDATIONS & ACTION PLAN", 20, yPos + 1.5);

  yPos += 15;

  // The Advice Text
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);
  
  // Wrap text to fit page width
  const splitText = doc.splitTextToSize(result.advice, pageWidth - 40);
  doc.text(splitText, 20, yPos);

  yPos += (splitText.length * 7) + 10;

  // --- 5. STANDARD PROTOCOLS (Static Logic based on Result) ---
  doc.setFont('helvetica', 'bold');
  doc.text("Standard Operating Procedures (SOP):", 20, yPos);
  yPos += 8;
  doc.setFont('helvetica', 'normal');

  let sopText = [];
  if (isHealthy) {
    sopText = [
      "- Continue standard feeding schedule (3x daily).",
      "- Maintain water pH between 7.5 - 8.5.",
      "- Perform routine visual checks every 48 hours."
    ];
  } else {
    sopText = [
      "- IMMEDIATE ACTION: Isolate the affected pond/tank.",
      "- Stop water exchange to prevent pathogen spread.",
      "- Collect samples for lab verification (PCR Test).",
      "- Increase aeration to reduce stress on stock."
    ];
  }

  sopText.forEach(line => {
    doc.text(line, 20, yPos);
    yPos += 7;
  });

  // --- 6. FOOTER ---
  doc.setDrawColor(200, 200, 200);
  doc.line(15, 270, pageWidth - 15, 270);
  
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("This report is generated by the AquaSmart AI Neural Network. It is an assistive tool and does not replace", pageWidth / 2, 275, { align: 'center' });
  doc.text("professional veterinary diagnosis. Please consult a specialist for confirmation.", pageWidth / 2, 279, { align: 'center' });

  // Save File
  doc.save(`AquaSmart_Report_${Date.now()}.pdf`);
};